name: Deploy Decentralized Mainnet

on:
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy to the decentralized Graph network
    steps:
      - uses: lidofinance/check-user-permission@v2.0.1
        with:
          require: 'admin'
      - uses: actions/checkout@v2
      - name: Install Graph cli and deploy
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: |
          yarn global add @graphprotocol/graph-cli
          echo "$(yarn global bin)" >> $GITHUB_PATH
      - run: yarn install --immutable
      - run: graph codegen subgraph.mainnet.yaml
      - run: graph build subgraph.mainnet.yaml
      - run: graph deploy --studio --deploy-key ${{ secrets.THEGRAPH_DECENTRALIZED_TOKEN }} --version-label ${{ github.event.inputs.version }} lidofinance/lido subgraph.mainnet.yaml
