name: Deploy Decentralized Mainnet

on:
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy to the decentralized Graph network
    steps:
      - uses: lidofinance/check-user-permission@v3
        with:
          require: 'admin'
      - uses: actions/checkout@v3
      - name: Install Graph cli and deploy
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> "$GITHUB_OUTPUT"
      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --immutable
      - run: yarn codegen
      - run: yarn build
      - run: yarn graph deploy --studio --deploy-key ${{ secrets.THEGRAPH_DECENTRALIZED_TOKEN }} --version-label ${{ github.event.inputs.version }} lido --network mainnet
