name: Deploy Local Testnet

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Deploying to local graph node
    steps:
      - uses: lidofinance/check-user-permission@v3
        with:
          require: 'admin'
      - uses: actions/checkout@v3
      - name: Install Graph cli and deploy
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> "$GITHUB_OUTPUT"
      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --immutable
      - run: yarn codegen
      - run: yarn build-testnet
      - run: yarn graph deploy --access-token '${{ secrets.AUTH_TOKEN_TESTNET }}' --node '${{ secrets.GRAPH_NODE_TESTNET }}' --ipfs '${{ secrets.GRAPH_IPFS_TESTNET }}' --headers '${{ secrets.IPFS_AUTH_TESTNET }}' lidofinance/lido-testnet --network goerli -l v2.0.0
