name: Test Totals Testnet

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Testing totals on Testnet
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: cp .env.testnet.example .env
      - run: yarn install --immutable
      - name: Notify about environment preparation failure
        uses: lidofinance/action-discord@0.3.2
        with:
          args: |
            Unable to run `${{ github.workflow }}` workflow.
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        if: ${{ failure() }}
      - run: yarn test:totals
        env:
          RPC: ${{ secrets.RPC_TESTNET }}
        id: test
      - name: Notify about failed test run
        uses: lidofinance/action-discord@0.3.2
        with:
          args: |
            ${{ github.workflow }} has been failed!
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        if: ${{ failure() && steps.test.conclusion == 'failure' }}
