name: Test Totals Testnet

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Testing totals on Testnet
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --immutable
      - run: yarn test:totals
        env:
          SUBGRAPH_NAME: lidofinance/lido-testnet
          GRAPH: https://api.thegraph.com/subgraphs/name/lidofinance/lido-testnet
          GRAPH_MONITORING: https://api.thegraph.com/index-node/graphql
          RPC: ${{ secrets.RPC_TESTNET }}
          LIDO_ADDRESS: '0x1643E812aE58766192Cf7D2Cf9567dF2C37e9B7F'
          RPC_SYNC_BLOCK: 1
